name: todo
description: A sample command-line application with basic argument parsing.

environment:
  sdk: ">=3.0.0 <4.0.0"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  tuple: ^2.0.0
  socket_io_client: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.1.6
  connectivity_plus: ^6.0.1
  shared_preferences: ^2.0.15
  flutter_svg: ^2.0.7
  carousel_slider: ^4.1.1
  flutter_spinkit: ^5.1.0
  flutter_keyboard_visibility: ^6.0.0
  clipboard: ^0.1.3
  photo_view: ^0.14.0
  flutter_local_notifications: ^17.0.0
  #  appsflyer_sdk: ^6.5.2+2
  app_tracking_transparency: ^2.0.2+4
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  qr_flutter: ^4.0.0
  #  storyly_flutter: ^1.24.1
  dotted_border: ^2.0.0+2
  image_picker: ^1.0.2
  flutter_slidable: ^3.1.0
  fading_edge_scrollview: ^3.0.0
  async: ^2.8.2
  timer_count_down: ^2.2.1
  flutter_countdown_timer: ^4.1.0
  dropdown_button2: 1.9.4  # v2 available
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.1.4
  video_player: ^2.2.13
  url_launcher: ^6.1.9
  move_to_background: ^1.0.2
  open_mail_app: ^0.4.5
  modal_bottom_sheet: ^3.0.0-pre
  flutter_branch_sdk: 6.9.0  # v7 available
  facebook_app_events: ^0.19.2
  marquee: ^2.2.3
  marquee_text: ^2.5.0+1
  share: ^2.0.4
  #  flutter_social_content_share: ^1.0.2
  flutter_pw_validator: ^1.2.1
  mask_text_input_formatter: ^2.8.0
  get: ^4.6.6
  get_storage: ^2.1.1
  calendar_date_picker2: ^1.0.2
  firebase_analytics: ^10.10.7
  firebase_storage: ^11.7.7
  firebase_auth: ^4.20.0
  firebase_app_installations: ^0.2.5+7
  fluttertoast: ^8.2.5
  cloud_firestore: ^4.17.5




flutter:
  uses-material-design: true


flutter_icons:
  image_path: "assets/res/ic_launcher.png"
  image_path_ios: "assets/res/ic_launcher.png"
  adaptive_icon_background: "assets/res/ic_launcher.png"
  adaptive_icon_foreground: "assets/res/ic_launcher.png"
  android: true
  ios: true

